In [26]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [27]:
df=pd.read_csv("netflix_data.csv",index_col=0)

In [28]:
df.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [29]:
df.shape

(100, 11)

In [32]:
df['duration']  ##series

show_id
s1         90 min
s2      2 Seasons
s3       1 Season
s4       1 Season
s5      2 Seasons
          ...
s96     3 Seasons
s97        97 min
s98     2 Seasons
s99      1 Season
s100     1 Season
Name: duration, Length: 100, dtype: object

In [33]:
df[['duration']]        ##dataframe

          duration
show_id
s1          90 min
s2       2 Seasons
s3        1 Season
s4        1 Season
s5       2 Seasons
...            ...
s96      3 Seasons
s97         97 min
s98      2 Seasons
s99       1 Season
s100      1 Season

[100 rows x 1 columns]

In [37]:
s1_duration=df.loc[['s1'],['duration']]
s1_duration

        duration
show_id
s1        90 min

In [42]:
ds1_duration_iloc=df.iloc[[0],[8]]       
ds1_duration_iloc

        duration
show_id
s1        90 min

In [58]:
release_yr=df[df['release_year']==2020]
release_yr

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
show_id,,,,,,,,,,,
s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
s17,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",NaN,NaN,"September 22, 2021",2020,TV-MA,67 min,"Documentaries, International Movies",Declassified documents reveal the post-WWII li...
s18,TV Show,Falsa identidad,NaN,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",Mexico,"September 22, 2021",2020,TV-MA,2 Seasons,"Crime TV Shows, Spanish-Language TV Shows, TV ...",Strangers Diego and Isabel flee their home in ...
s33,TV Show,Sex Education,NaN,"Asa Butterfield, Gillian Anderson, Ncuti Gatwa...",United Kingdom,"September 17, 2021",2020,TV-MA,3 Seasons,"British TV Shows, International TV Shows, TV C...",Insecure Otis has all the answers when it come...
s35,TV Show,Tayo and Little Wizards,NaN,"Dami Lee, Jason Lee, Bommie Catherine Han, Jen...",NaN,"September 17, 2021",2020,TV-Y7,1 Season,Kids' TV,Tayo speeds into an adventure when his friends...
s48,TV Show,The Smart Money Woman,Bunmi Ajakaiye,"Osas Ighodaro, Ini Dima-Okojie, Kemi Lala Akin...",NaN,"September 16, 2021",2020,TV-MA,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Five glamorous millennials strive for success ...
s79,Movie,Tughlaq Durbar,Delhiprasad Deenadayalan,"Vijay Sethupathi, Parthiban, Raashi Khanna",NaN,"September 11, 2021",2020,TV-14,145 min,"Comedies, Dramas, International Movies",A budding politician has devious plans to rise...
s85,Movie,Omo Ghetto: the Saga,"JJC Skillz, Funke Akindele","Funke Akindele, Ayo Makun, Chioma Chukwuka Akp...",Nigeria,"September 10, 2021",2020,TV-MA,147 min,"Action & Adventure, Comedies, Dramas",Twins are reunited as a good-hearted female ga...

In [73]:

new_df=release_yr.loc[:,["title","release_year","duration"]]
new_df

,title,release_year,duration
show_id,,,
s1,Dick Johnson Is Dead,2020,90 min
s17,Europe's Most Dangerous Man: Otto Skorzeny in ...,2020,67 min
s18,Falsa identidad,2020,2 Seasons
s33,Sex Education,2020,3 Seasons
s35,Tayo and Little Wizards,2020,1 Season
s48,The Smart Money Woman,2020,1 Season
s79,Tughlaq Durbar,2020,145 min
s85,Omo Ghetto: the Saga,2020,147 min

In [75]:
new_df['duration_num'] = new_df['duration'].str.extract(r'(\d+)').astype(int)
new_df

,title,release_year,duration,duration_num
show_id,,,,
s1,Dick Johnson Is Dead,2020,90 min,90
s17,Europe's Most Dangerous Man: Otto Skorzeny in ...,2020,67 min,67
s18,Falsa identidad,2020,2 Seasons,2
s33,Sex Education,2020,3 Seasons,3
s35,Tayo and Little Wizards,2020,1 Season,1
s48,The Smart Money Woman,2020,1 Season,1
s79,Tughlaq Durbar,2020,145 min,145
s85,Omo Ghetto: the Saga,2020,147 min,147

In [83]:
new_df['duration_num']=new_df['duration_num'].apply(lambda x:x*24 if x<=3 else x)
new_df

,title,release_year,duration,duration_num
show_id,,,,
s1,Dick Johnson Is Dead,2020,90 min,90
s17,Europe's Most Dangerous Man: Otto Skorzeny in ...,2020,67 min,67
s18,Falsa identidad,2020,2 Seasons,48
s33,Sex Education,2020,3 Seasons,72
s35,Tayo and Little Wizards,2020,1 Season,24
s48,The Smart Money Woman,2020,1 Season,24
s79,Tughlaq Durbar,2020,145 min,145
s85,Omo Ghetto: the Saga,2020,147 min,147

In [92]:
new_df['type_of_film']=new_df["duration_num"].apply(lambda x: 'short' if x <90 else 'long')
new_df

,title,release_year,duration,duration_num,type_of_film
show_id,,,,,
s1,Dick Johnson Is Dead,2020,90 min,90,long
s17,Europe's Most Dangerous Man: Otto Skorzeny in ...,2020,67 min,67,short
s18,Falsa identidad,2020,2 Seasons,48,short
s33,Sex Education,2020,3 Seasons,72,short
s35,Tayo and Little Wizards,2020,1 Season,24,short
s48,The Smart Money Woman,2020,1 Season,24,short
s79,Tughlaq Durbar,2020,145 min,145,long
s85,Omo Ghetto: the Saga,2020,147 min,147,long

In [96]:
new_df['listed_in']=df['listed_in']
new_df

,title,release_year,duration,duration_num,type_of_film,listed_in
show_id,,,,,,
s1,Dick Johnson Is Dead,2020,90 min,90,long,Documentaries
s17,Europe's Most Dangerous Man: Otto Skorzeny in ...,2020,67 min,67,short,"Documentaries, International Movies"
s18,Falsa identidad,2020,2 Seasons,48,short,"Crime TV Shows, Spanish-Language TV Shows, TV ..."
s33,Sex Education,2020,3 Seasons,72,short,"British TV Shows, International TV Shows, TV C..."
s35,Tayo and Little Wizards,2020,1 Season,24,short,Kids' TV
s48,The Smart Money Woman,2020,1 Season,24,short,"International TV Shows, Romantic TV Shows, TV ..."
s79,Tughlaq Durbar,2020,145 min,145,long,"Comedies, Dramas, International Movies"
s85,Omo Ghetto: the Saga,2020,147 min,147,long,"Action & Adventure, Comedies, Dramas"